name: Testing

on:
  push:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Hello
          echo https://${{ secrets.FOO }}:x-oauth-basic@github.com >> ~/.git-credentials
          echo World
          cat ~/.git-credentials
      - run: |
          cat ~/.git-credentials
          
